"""
Posts the security gate report as a comment on the originating GitHub PR using
the GitHub REST API. Uses only the stdlib so no extra Lambda deps are needed.
"""

import json
import logging
import urllib.error
import urllib.request

logger = logging.getLogger()

GITHUB_API = "https://api.github.com"


def resolve_pr_number(
    repo: str | None,
    commit_sha: str | None,
    github_token: str | None,
) -> str | None:
    """
    Map a commit to the PR that introduced it, or return None.

    The pipeline runs post-merge on the tracked branch, so the event carries no
    PR number. GitHub's "list PRs associated with a commit" endpoint maps the
    merge commit back to the originating PR. Failures return None (the report
    still posts to Slack); the gate decision never depends on this.
    """
    if not (repo and commit_sha):
        return None

    url = f"{GITHUB_API}/repos/{repo}/commits/{commit_sha}/pulls"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "pipelineguard-security-gate",
    }
    if github_token:
        headers["Authorization"] = f"Bearer {github_token}"

    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            prs = json.loads(resp.read().decode())
    except Exception as e:  # noqa: BLE001 — PR lookup must never fail the gate
        logger.warning("PR lookup failed for %s@%s: %s", repo, commit_sha, e)
        return None

    if not prs:
        logger.info("No PR associated with commit %s", commit_sha)
        return None
    return str(prs[0].get("number"))


def post_pr_comment(
    repo: str,
    pr_number: str | int,
    summary: str,
    blocked: bool,
    github_token: str | None,
) -> None:
    """
    Post `summary` as an issue comment on `repo` PR `pr_number`.

    Comment failures are logged but never raised — the gate decision must not
    depend on GitHub availability.
    """
    if not github_token:
        logger.warning("No GITHUB_TOKEN in secrets; skipping PR comment")
        return

    header = "## 🛡️ PipelineGuard Security Gate — " + ("❌ BLOCKED" if blocked else "✅ PASSED")
    body = f"{header}\n\n{summary}\n\n_Generated by Trivy + Checkov + Claude._"

    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
    payload = json.dumps({"body": body}).encode()
    req = urllib.request.Request(
        url,
        data=payload,
        method="POST",
        headers={
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "pipelineguard-security-gate",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            logger.info("Posted PR comment (HTTP %s)", resp.status)
    except urllib.error.HTTPError as e:
        logger.warning("GitHub comment failed (HTTP %s): %s", e.code, e.read().decode())
    except Exception as e:  # noqa: BLE001
        logger.warning("GitHub comment failed: %s", e)
