"""
Posts the security gate report as a comment on the originating GitHub PR using
the GitHub REST API. Uses only the stdlib so no extra Lambda deps are needed.
"""

import json
import logging
import urllib.error
import urllib.request

logger = logging.getLogger()

GITHUB_API = "https://api.github.com"


def post_pr_comment(
    repo: str,
    pr_number: str | int,
    summary: str,
    blocked: bool,
    github_token: str | None,
) -> None:
    """
    Post `summary` as an issue comment on `repo` PR `pr_number`.

    Comment failures are logged but never raised — the gate decision must not
    depend on GitHub availability.
    """
    if not github_token:
        logger.warning("No GITHUB_TOKEN in secrets; skipping PR comment")
        return

    header = "## 🛡️ PipelineGuard Security Gate — " + ("❌ BLOCKED" if blocked else "✅ PASSED")
    body = f"{header}\n\n{summary}\n\n_Generated by Trivy + Checkov + Claude._"

    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
    payload = json.dumps({"body": body}).encode()
    req = urllib.request.Request(
        url,
        data=payload,
        method="POST",
        headers={
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "pipelineguard-security-gate",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            logger.info("Posted PR comment (HTTP %s)", resp.status)
    except urllib.error.HTTPError as e:
        logger.warning("GitHub comment failed (HTTP %s): %s", e.code, e.read().decode())
    except Exception as e:  # noqa: BLE001
        logger.warning("GitHub comment failed: %s", e)
